# Generated by Django 2.0.3 on 2019-07-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='topping_options',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.ToppingOptions'),
        ),
    ]
