# Generated by Django 2.0.3 on 2019-07-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190721_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='topping_options',
            field=models.IntegerField(max_length=1),
        ),
        migrations.DeleteModel(
            name='ToppingOptions',
        ),
    ]
