# Generated by Django 2.0.3 on 2019-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190721_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='topping_options',
        ),
        migrations.AddField(
            model_name='item',
            name='number_of_toppings',
            field=models.IntegerField(default=0),
        ),
    ]
